site_name: "ACR Harmonized Data Model"
site_url: "https://anvilproject.github.io/acr-harmonized-data-model"
theme:
  name: readthedocs
plugins:
  - search
  - mermaid2
#markdown_extensions:
#  - toc:
#      permalink: true
docs_dir: anvil/docs
site_dir: docs
nav:
  - About: anvil.md
